
const tasksErrors = {
  listNotFound: 'Lista n√£o encontrada!',
};
  
export default tasksErrors;
  